### ISSUE TITLE
Problem in starting client

### ISSUE THREAD

**Issue by i-Naji** [pyrogram/pyrogram#101]
```
  File "/usr/local/lib/python3.5/dist-packages/pyrogram/client/client.py", line 216, in start
    self.session.start()
  File "/usr/local/lib/python3.5/dist-packages/pyrogram/session/session.py", line 164, in start
    raise e
  File "/usr/local/lib/python3.5/dist-packages/pyrogram/session/session.py", line 134, in start
    self.current_salt = self._send(functions.GetFutureSalts(1)).salts[0]
  File "/usr/local/lib/python3.5/dist-packages/pyrogram/session/session.py", line 404, in _send
    "Error code {}".format(result.error_code)
Exception: [17] msg_id too high, the client time has to be synchronized
```
its first start!

**Comment by i-Naji** [comment]
This error was due to wrong date on my side, I synced my clock and Everything is fine :)

**Comment by delivrance** [comment]
Yep, people often report this. Looks like the error message is too cryptic to understand that they need to sync their clocks.

**Comment by qiyuyi** [comment]
> This error was due to wrong date on my side, I synced my clock and Everything is fine :)

Hi, i tried to change my system time but it didn't work, could you please tell me how to synce the clock

**Comment by ColinTheShark** [comment]
> could you please tell me how to synce the clock

This Issue is from over a year ago. I suggest using Google on [how to sync your system clock](http://google.com/search?q=how%20to%20sync%20system%20clock).

**Comment by qiyuyi** [comment]
> > could you please tell me how to synce the clock
> 
> This Issue is from over a year ago. I suggest using Google on [how to sync your system clock](http://google.com/search?q=how%20to%20sync%20system%20clock).


Thank you very much, I ran the program in docker, so I did not find the source of the problem at the beginning, but now it has been resolved.

**Comment by MrGeRoI** [comment]
Is this still relevant? I tried different options:
```
time.windows.com
time.nist.gov
time.google.com
```
None of them worked. The only thing is that the error has changed from too low to too high.

**Comment by billouetaudrey** [comment]
Do systemctl status systemd-timesyncd

**Comment by MrGeRoI** [comment]
> Do `systemctl status systemd-timesyncd `
> If disable , do `systemctl enable systemd-timesyncd && systemctl start systemd-timesyncd `
> then
> follow this https://www.maketecheasier.com/timedatectl-control-system-time-date-linux/
Sorry i hadn't say that i have Windows 10.
I tried something. I started the Windows time service, which was turned off. It's called W32Time. But the problem with msg_id was not solved.

**Comment by billouetaudrey** [comment]
Hi,

Sorry but it's not fixed for me too :( Crashed after few minutes with same error :(

**Comment by delivrance** [comment]
This issue is not relevant anymore in latest versions. If you believe there's an issue with the library open a new issue and follow the template.

**Comment by kai3341** [comment]
I have `Pyrogram==1.2.9`

Once per day client fail with `Exception: [16] msg_id too low, the client time has to be synchronized`
Is it the same error?

**Comment by billouetaudrey** [comment]
> I have `Pyrogram==1.2.9`
> 
> Once per day client fail with `Exception: [16] msg_id too low, the client time has to be synchronized`
> Is it the same error?

Not same but i have this error too 😔

**Comment by jimmygns** [comment]
> > I have `Pyrogram==1.2.9`
> > Once per day client fail with `Exception: [16] msg_id too low, the client time has to be synchronized`
> > Is it the same error?
> 
> Not same but i have this error too 😔

did you ever get it to work again? I started seeing the same error recently and followed https://tecadmin.net/synchronizing-a-linux-system-clock-with-ntp-server/, but no luck.

**Comment by billouetaudrey** [comment]
Hi, nope it was program version issue
But since 2/3 days I have same issue again, with some bot (I host some telegram bot for people)
The issue is old pyrogram version with DC1 for now
Work with Pyrogram 2.x

**Comment by billouetaudrey** [comment]
> > 
> 
> hmm, I'm running the 2.x version.
> 
> Pyrogram==2.0.38
> 
> it throws the same error on both my cloud VM and my MacBook. Not sure what actually went wrong.

Try 2.0.106

**Comment by jimmygns** [comment]
> > > 
> > 
> > 
> > hmm, I'm running the 2.x version.
> > Pyrogram==2.0.38
> > it throws the same error on both my cloud VM and my MacBook. Not sure what actually went wrong.
> 
> Try 2.0.106

yeah I tried no luck tho...

**Comment by tangyoha** [comment]
> > > 
> > 
> > 
> > hmm, I'm running the 2.x version.
> > Pyrogram==2.0.38
> > it throws the same error on both my cloud VM and my MacBook. Not sure what actually went wrong.
> 
> Try 2.0.106

@billouetaudrey hi, which commit fix it?

**Comment by inuseki** [comment]
seems like a package issue, tried on few PC's still facing this error

**Comment by Nusab19** [comment]
Guys, here's a fix:

```
pip install Pyrogram==2.0.63
```

Solution by this guy: t.me/Wizard_iv

**Comment by billouetaudrey** [comment]
Me work with DC5 + Pyro 1.4.7

**Comment by aalnajim** [comment]
Try:

`pip3 install -U pyrogram`

**Comment by Nusab19** [comment]
> Try:
> 
> `pip3 install -U pyrogram`

Got fixed by 2.0.106 meaning the lastest. But then this version didn’t work either. 
Idk how it got fixed automatically

**Comment by techkuz** [comment]
remove session file in your prj

**Comment by CodeOfDestruction** [comment]
how to fix this without upgrading pyrogram 1.5 ? Thanks

**Comment by Nusab19** [comment]
> how to fix this without upgrading pyrogram 1.5 ? Thanks

Try upgrading to the latest version and check your device's datetime

**Comment by Nusab19** [comment]
@CodeOfDestruction Well, I've been using the latest pyrogram for a while now. And I didn't got any issues with it. Neither in my system, or in other servers.

Where are you running it tho?

**Comment by amirroox** [comment]
> @CodeOfDestruction Well, I've been using the latest pyrogram for a while now. And I didn't got any issues with it. Neither in my system, or in other servers.
> 
> Where are you running it tho?

Do you still have a problem?

**Comment by Nusab19** [comment]
@amirroox Just tested `pyrogram==2.0.106` in pydroid3 and it worked fine.

**Comment by vincentkaleba** [comment]
⛔️erreur: The msgid is too low, the client time has to be synchronized.
🥹

**Comment by Nusab19** [comment]
@vincentkaleba Where are you running it?

If you're running it locally, then make sure that "Set time automatically" option is selected and not the manual one.

![image](https://github.com/user-attachments/assets/1c893437-07f0-4092-8a36-cd413805e968)
